login_username="xx"
#12306登录密码
login_password="xx"
#12306登录账号真实姓名
login_realname="xx"
#出发地
from_station="北京"
#目的地
to_station="天津"
#出发时间
train_date="2019-01-20"
#首选车次
train_no="G37,G301"
#首选座位
train_seat_type="二等座,一等座"
#乘客姓名(必须提前添加到12306登录账户的乘客名单中)
passenger_name="xxx"
#乘客身份证(必须提前添加到12306登录账户的乘客名单中)
passenger_id="xx"
#乘客手机号(必须提前添加到12306登录账户的乘客名单中)
passenger_phone="xx"
#微信消息通知人(必须是你微信好友)
report_to_name="xx"
